preserve_hierarchy: true
files:
  - source: /Stratum.Droid/Resources/values/strings.xml
    translation: /Stratum.Droid/Resources/values-%two_letters_code%/strings.xml
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        zh-TW: zh-rTW
        pt-BR: pt-rBR

  - source: /Stratum.WearOS/Resources/values/strings.xml
    translation: /Stratum.WearOS/Resources/values-%two_letters_code%/strings.xml
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        zh-TW: zh-rTW
        pt-BR: pt-rBR

  - source: /fastlane/metadata/android/en-US/short_description.txt
    translation: /fastlane/metadata/android/%locale%/short_description.txt

  - source: /fastlane/metadata/android/en-US/full_description.txt
    translation: /fastlane/metadata/android/%locale%/full_description.txt
